# https://blog.csdn.net/u014361775/article/details/78865582
sudo apt-get update
sudo apt-get install -y python-software-properties software-properties-common
sudo add-apt-repository -y ppa:chris-lea/node.js
sudo apt-get update

sudo apt-get install -y nodejs
sudo apt install -y nodejs-legacy
sudo apt install -y npm

sudo npm config set registry https://registry.npm.taobao.org
sudo npm config list

