# Generated by Django 2.0.5 on 2018-07-02 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlpage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawlpage', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='types',
            field=models.SmallIntegerField(choices=[(0, '匹配关键字'), (1, '翻页关键字')], default=0),
        ),
    ]
