# Generated by Django 2.0.5 on 2018-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0002_auto_20180624_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('site', models.URLField(blank=True, default='')),
                ('code', models.TextField()),
                ('status', models.SmallIntegerField(default=0)),
                ('highlighted', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
