# Generated by Django 2.0.5 on 2018-06-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m', '0003_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='linenos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webpage',
            name='style',
            field=models.CharField(choices=[('abap', 'abap'), ('algol', 'algol'), ('algol_nu', 'algol_nu'), ('arduino', 'arduino'), ('autumn', 'autumn'), ('borland', 'borland'), ('bw', 'bw'), ('colorful', 'colorful'), ('default', 'default'), ('emacs', 'emacs'), ('friendly', 'friendly'), ('fruity', 'fruity'), ('igor', 'igor'), ('lovelace', 'lovelace'), ('manni', 'manni'), ('monokai', 'monokai'), ('murphy', 'murphy'), ('native', 'native'), ('paraiso-dark', 'paraiso-dark'), ('paraiso-light', 'paraiso-light'), ('pastie', 'pastie'), ('perldoc', 'perldoc'), ('rainbow_dash', 'rainbow_dash'), ('rrt', 'rrt'), ('tango', 'tango'), ('trac', 'trac'), ('vim', 'vim'), ('vs', 'vs'), ('xcode', 'xcode')], default='friendly', max_length=100),
        ),
        migrations.AddField(
            model_name='webpage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
